XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XE.VSSaturday.RazorPages.Web.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace XE.VSSaturday.RazorPages.Web.Pages
{
    public class ContactModel : PageModel
    {

        [BindProperty]
        public ContactFormModel Input { get; set; }

        public class ContactFormModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.MultilineText)]
            public string Text { get; set; }
        }


        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                // TODO: invio della mail con il testo della form
                //
                var email = Input.Email;
                var text = Input.Text;

                return RedirectToPage("./ContactOk");

            }

            // If we got this far, something failed, redisplay form
            return Page();
        }

    
    }
}

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/ContactOk.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XE.VSSaturday.RazorPages.Web.Pages
{
    public class ContactOkModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XE.VSSaturday.RazorPages.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XE.VSSaturday.RazorPages.Web.Pages
{
    public class IndexModel : PageModel
    {

        [BindProperty]
        public NewsletterFormModel Input { get; set; }

        [TempData]
        public string NewsletterJoinMessage { get; set; }

        public class NewsletterFormModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }


        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostJoinListXEAsync()
        {
            if (ModelState.IsValid)
            {
                // TODO: Gestire l'iscrizione alla newsletter
                //
                this.NewsletterJoinMessage = "Sei ora iscritto alla newsletter di XE";
                return RedirectToPage("./Newsletter/Ok");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostJoinList1nn0vaAsync()
        {
            if (ModelState.IsValid)
            {
                // TODO: Gestire l'iscrizione alla newsletter
                //
                this.NewsletterJoinMessage = "Sei ora iscritto alla newsletter di 1nn0va";
                return RedirectToPage("./Newsletter/Ok");
            }

            return Page();
        }
    }
}

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/Newsletter/Ok.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XE.VSSaturday.RazorPages.Web.Pages.Newsletter
{
    public class OkModel : PageModel
    {
        [TempData]
        public string NewsletterJoinMessage { get; set; }

        public void OnGet()
        {

        }
    }
}

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XE.VSSaturday.RazorPages.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contatti";
}

<section>
    <form method="post">
        <h2>@ViewData["Title"]</h2>
        <h4>Compila la form e verrai contattato (forse) al più presto</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Input.Email"></label>
            <input asp-for="Input.Email" class="form-control" />
            <span asp-validation-for="Input.Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Input.Text"></label>
            <textarea asp-for="Input.Text" class="form-control" rows="10"></textarea>
            <span asp-validation-for="Input.Text" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-default">Invia</button>
        </div>
    </form>
</section>
<br>





@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/ContactOk.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contatti";
}
<h2>@ViewData["Title"]</h2>

<div class="alert alert-success" role="alert">
    Mail inviata con successo!
</div>

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1>Visual Studio Saturday</h1>
<p>Demo Razor Pages</p>
<p>2018.11.10</p>
<hr />
<section>
    <form method="POST">
        <h2>Newsletter</h2>
        <h4>Iscriviti alla newsletter per rimanere informato sui prossimi eventi</h4>
        <div class="form-group">
            <label asp-for="Input.Email"></label>
            <input asp-for="Input.Email" class="form-control" />
            <span asp-validation-for="Input.Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" asp-page-handler="JoinListXE" value="Join XE newsletter" />
            <input type="submit" asp-page-handler="JoinList1nn0va" value="Join 1nn0va newsletter" />
        </div>
    </form>
</section>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/Newsletter/Ok.cshtml
@page
@model XE.VSSaturday.RazorPages.Web.Pages.Newsletter.OkModel
@{
    ViewData["Title"] = "Iscrizione newsletter";
}

<h2>Iscrizione newsletter</h2>

@if (!string.IsNullOrWhiteSpace(Model.NewsletterJoinMessage))
{
    <div class="alert alert-success" role="alert">
        @Model.NewsletterJoinMessage
    </div>
}

XE.VSSaturday.RazorPages/XE.VSSaturday.RazorPages.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Andrea Dottor [Visual Studio Saturday 2018]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">Visual Studio Saturday</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/Speakers" asp-area="Agenda">Speakers</a></li>
                    <li><a asp-page="/Sessions" asp-area="Agenda">Sessioni</a></li>
                    <li><a asp-page="/Contact">Contatti</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Visual Studio Saturday - Andrea Dottor</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>